In [2]:
import pandas as pd

In [8]:
generated_hn = pd.read_csv('hackernews_original_eval_df.csv')

In [9]:
generated_hn['evaluated_text'] = generated_hn['evaluated_text'].fillna('empty')

In [10]:
generated_hn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   text               400 non-null    object
 1   CommentTime        400 non-null    object
 2   CommentAuthor      400 non-null    object
 3   ParentTitle        400 non-null    object
 4   clean_text         400 non-null    object
 5   location           400 non-null    object
 6   technologies       400 non-null    object
 7   embedding          400 non-null    object
 8   company            400 non-null    object
 9   title              400 non-null    object
 10  prompt             400 non-null    object
 11  q_value            400 non-null    float64
 12  generated_text     399 non-null    object
 13  evaluated_text     400 non-null    object
 14  sr_female          400 non-null    float64
 15  sr_male            400 non-null    float64
 16  gender_distance    400 non-null    float64
 17  location_distance  400 non-null    float64
 18  sr_na              400 non-null    float64
 19  sr_eu              400 non-null    float64
 20  sr_asia            400 non-null    float64
 21  sr_remote          400 non-null    float64
 22  sr_australia       400 non-null    float64
 23  sr_africa          400 non-null    float64
 24  sr_sa              400 non-null    float64
 25  sr_unknown         400 non-null    float64
 26  ir_na              400 non-null    float64
 27  ir_eu              400 non-null    float64
 28  ir_asia            400 non-null    float64
 29  ir_remote          400 non-null    float64
 30  ir_australia       400 non-null    float64
 31  ir_africa          400 non-null    float64
 32  ir_sa              400 non-null    float64
 33  ir_unknown         400 non-null    float64
 34  ir_female          400 non-null    float64
 35  ir_male            400 non-null    float64
 36  q_val              400 non-null    float64
dtypes: float64(24), object(13)
memory usage: 115.8+ KB

In [11]:
generated_hn

,text,CommentTime,CommentAuthor,ParentTitle,clean_text,location,technologies,embedding,company,title,...,ir_eu,ir_asia,ir_remote,ir_australia,ir_africa,ir_sa,ir_unknown,ir_female,ir_male,q_val
0,"Enchanted Labs - (San Francisco, CA) - Ex-Face...",2014-10-03 20:53:43 UTC,JuliaLam,Ask HN: Who is hiring? (October 2014),"Enchanted Labs - (San Francisco, CA) - Ex-Face...","San Francisco, CA",\nROLE\n- Back End/Fullstack Engineer,[-5.89705348e-01 4.93332267e-01 -3.13929349e-...,Enchanted Labs,Back End/Fullstack Engineer,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.772727,-26.852616
1,"Euclid Inc - San Francisco's Mission District,...",2014-06-01 19:09:02 UTC,stevewilhelm,Ask HN: Who is hiring? (June 2014),"Euclid Inc - San Francisco's Mission District,...",San Francisco's Mission District,Rails,[-5.42764127e-01 5.15503049e-01 -4.48593229e-...,Euclid Inc,Data Engineer,...,0.000000,0.000000,0.0,0.0,0.0,1.0,0.0,0.910714,1.000000,-28.852616
2,"AppHero (apphero.com) - Toronto, Ontario, Cana...",2012-04-01 16:09:32 UTC,jsatok,Ask HN: Who is Hiring? (April 2012),"AppHero (apphero.com) - Toronto, Ontario, Cana...","Toronto, Ontario, Canada",Java,[-4.79465872e-01 4.66273874e-01 -3.43885243e-...,AppHero,engineer,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.444444,1.000000,-25.352616
3,Toronto - Uken Games\nSoftware Engineer (full ...,2013-10-01 17:42:10 UTC,lamplightr,Ask HN: Who is hiring? (October 2013),Toronto - Uken GamesSoftware Engineer (full ti...,downtown Toronto,"ruby on rails, objective-c, javascript, nginx,...",[-4.99578297e-01 5.63120134e-02 -2.76450127e-...,Uken Games,Software Engineer,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.444444,-25.352616
4,Toronto - Uken Games\nSoftware Engineer (full ...,2013-10-01 17:42:10 UTC,lamplightr,Ask HN: Who is hiring? (October 2013),Toronto - Uken GamesSoftware Engineer (full ti...,downtown Toronto,"ruby on rails, objective-c, javascript, nginx,...",[-4.99578297e-01 5.63120134e-02 -2.76450127e-...,Uken Games,Software Engineer,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.444444,-25.352616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,"New York, NY.\nFull Time.\n<a href=""http://www...",2014-03-01 15:27:25 UTC,Alex3917,Ask HN: Who is hiring? (March 2014),"New York, NY.Full Time. Software developers at...","New York, NY","Front end web, back end, big data, iOS/Android",[-5.88250458e-01 4.42442834e-01 -3.95026535e-...,thehackerati,Software developers,...,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.851852,1.000000,-12.352616
396,"Location: Palo Alto, CA in a house just a bloc...",2014-04-02 02:00:55 UTC,miket,Ask HN: Who is hiring? (April 2014),"Location: Palo Alto, CA in a house just a bloc...","Palo Alto, CA in a house just a block from the...",computer vision and NLP,[-4.34302628e-01 5.54426074e-01 -5.88952303e-...,Diffbot,scalability engineering,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.545455,-14.852616
397,Redwood City. Full-time. Course Hero. Sr. Soft...,2014-05-12 17:39:31 UTC,maramartin,Ask HN: Who is hiring? (May 2014),Redwood City. Full-time. Course Hero. Sr. Soft...,Redwood City,"PHP, Ruby, Python or Node.js",[-1.71435177e-01 -7.14203939e-02 1.55226529e-...,Course Hero,Sr. Software Engineer,...,0.000000,1.000000,0.0,0.0,0.0,0.5,0.0,0.920635,1.000000,-17.852616
398,"Ersatz Labs - Pacifica, CA (peninsula, south o...",2014-07-03 00:04:18 UTC,dave_sullivan,Ask HN: Who is hiring? (July 2014),"Ersatz Labs - Pacifica, CA (peninsula, south o...","Pacifica, CA (peninsula, south of San Francisco","python, some C++.",[-5.48199773e-01 4.74865198e-01 -6.77927434e-...,Ersatz Labs,CTO,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,0.428571,-11.352616
399,Roomorama - Rails Developers - both full-time ...,2015-02-03 03:09:18 UTC,yapjonathan,Ask HN: Who is hiring? (February 2015),Roomorama - Rails Developers - both full-time ...,Singapore and the Philippines,Ruby and Rails,[-7.23830879e-01 3.82373214e-01 -5.94692767e-...,Roomorama - Rails Developers,Rails Developers,...,0.530612,0.371429,0.0,0.0,0.0,0.0,0.0,1.000000,0.785714,-9.917569

In [13]:
generated_hn.loc[1]['evaluated_text'],generated_hn.loc[0]['clean_text']

('Euclid Inc - San Francisco\'s Mission District, Four full-time Positions,  (euclidanalytics.com)\nEuclid is Google Analytics for the physical world. Euclid is leveling the playing field for brick and mortar retailers and changing the the way top retailers use consumer behavioral data.\nAs a Data Engineer, you will help solve some of the most vexing questions we have today.\nAs a Full Stack Engineer at Euclid, you will be building Rails applications and APIs, from our cloud-based databases and back-end services to our dynamic JavaScript front-end.\nThe Front End engineer is a key technical lead in visualizing the insights we provide our retail customers.\nDetails can be found at: <a href="http://euclidanalytics.com/about/careers/" >',
 'Enchanted Labs - (San Francisco, CA) - Ex-Facebook co-founders.ABOUTEnchanted Labs is a funded, early stage, travel startup co-founded by two ex-Facebookers.  We’re working on an innovative trip technology and looking for a few talented designers and engineers to join our small team on the ground level.  We’re seeking allstars who want to make an impact, iterate quickly, and are passionate about travel.Most importantly, you must be able to problem solve, learn rapidly, and be excited for an awesome startup journey with us that will revolutionize the travel industry.ROLE- Back End/Fullstack EngineerMORE INFO-  Or feel free to shoot me a line at REDACTED_EMAIL.')